#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/Applications/Racket v7.4/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-I' 'scheme/init' '-qt-' '/Users/jaejin/Work/racket/racket_webserver/server.rkt'  ${1+"$@"}
